name: dev
description: Dev tools and widgets for Flutter applications.
version: 1.0.0
homepage: https://github.com/AndreBaltazar8/flutter_dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gestures: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
