name: dev
description: Dev tools and widgets for Flutter applications.
version: 0.0.2
author: André Baltazar <me@andrebaltazar.com>
homepage: https://github.com/AndreBaltazar8/flutter_dev

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gestures: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
